### PR TITLE
Add codemirror to existing text areas

### PR DESCRIPTION
**Pull request by sivsushruth**
codemirror

@pjhampton @benoitc Thoughts ?

### CODE REVIEW

**Comment by pjhampton** [comment]
Wow! Great job @sivsushruth 

This looks awesome :+1:

**Comment by ermouth** [comment]
Just built from PR, works like a charm )) Great! 👏

https://gist.github.com/ermouth/953691b6b62c9cab4ff6 
Here is an old gist showing how to use Uglify to both validate JS and figure out global vars used. To make it work fine, anonymous function‘s source must be wrapped with ().

**Comment by sivsushruth** [comment]
@pjhampton  @ermouth Thanks for the quick turnaround. 
Will work on this further.

**Comment by sivsushruth** [comment]
I intend to wrap up the editor functionality a bit more along with the validation @ermouth suggested. 
Although, do you guys think, the PR needs more work done before merging with master ?
If this is merged, can take this up for a new branch for 'futon-upgrade' and work on it further. 
Let me know

**Comment by benoitc** [comment]
i will test this morning :) imo if it works let's merge it and do the rest
in a separate patch :)

**Comment by benoitc** [comment]
merged. Thanks!

**Pull request merged**
