### PR TITLE
fix typos

### PR DESCRIPTION
**Pull request by jxub**
Hi!

Couldn't find the develop branch, just found these typos in the error message

### CODE REVIEW

**Review by pjhampton — APPROVED** [review]
Thanks. LGTM 👍

**Comment by pjhampton** [comment]
Thanks @jxub! No develop branch - you can just PR against master. 
Welcome BTW :)

**Comment by jxub** [comment]
Heh, thanks a bunch @pjhampton ;)
Is there anything else to contribute in the project (I see no open issues)?

**Comment by jxub** [comment]
I just seen the GSoC project idea for making an Elixir port to BarrelDB so I may as well apply, as it looks like a hell of an interesting task :)

**Comment by pjhampton** [comment]
NP @jxub :-) Cool to see that you are interested.
I believe most of the work happens over at https://gitlab.com/barrel-db these days. I'm not the biggest gitlab fan but @benoitc seems to like it ;)

**Pull request merged**
